name: Node.js Package

on:
    pull_request:
    push:
        branches: [main]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x, 14.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}
            - name: Node.JS ${{ matrix.node-version }} Setup
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm install --no-optional --no-shrinkwrap --no-package-lock
            - name: Lint Project
              run: npm run lint
            - name: Run Test
              run: npm test

    buildStorybookVersionReleasePublish:
        name: Build, Version, Release, Publish
        needs: test
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}
                  persist-credentials: false
            - name: Node.JS 14 Setup
              uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com/
            - name: Install Dependencies
              run: npm ci
            - name: Clean Build
              run: npm run clean-build
            - name: Build Files & Folder
              run: npm run build --if-present
            - name: Semantic Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GH_TOKEN }}
                  NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
            - name: Deploy Storybook
              run: npm run deploy-storybook -- --ci
              env:
                  GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}
